-- Create the prompts table
create table prompts (
  id bigint generated by default as identity (start with 6) primary key,
  title text not null,
  content text not null,
  category text not null,
  type text not null,
  is_favorite boolean default false,
  tags text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table prompts enable row level security;

-- Policies for prompts
create policy "Enable read access for all users" on prompts for select using (true);
create policy "Enable write access for all users" on prompts for insert with check (true);
create policy "Enable update access for all users" on prompts for update using (true);
create policy "Enable delete access for all users" on prompts for delete using (true);

-- Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table categories enable row level security;
create policy "Enable read access for all users" on categories for select using (true);
create policy "Enable insert access for all users" on categories for insert with check (true);
create policy "Enable update access for all users" on categories for update using (true);
create policy "Enable delete access for all users" on categories for delete using (true);

-- Types Table
create table types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table types enable row level security;
create policy "Enable read access for all users" on types for select using (true);
create policy "Enable insert access for all users" on types for insert with check (true);
create policy "Enable update access for all users" on types for update using (true);
create policy "Enable delete access for all users" on types for delete using (true);

-- Prompt Tags Table
create table prompt_tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table prompt_tags enable row level security;
create policy "Enable read access for all users" on prompt_tags for select using (true);
create policy "Enable insert access for all users" on prompt_tags for insert with check (true);
create policy "Enable update access for all users" on prompt_tags for update using (true);
create policy "Enable delete access for all users" on prompt_tags for delete using (true);

-- Insert default prompt tags
INSERT INTO prompt_tags (name) VALUES
  ('contesto'),
  ('istruzioni'),
  ('esempio'),
  ('output'),
  ('variabili')
ON CONFLICT (name) DO NOTHING;

-- Create the prompt_revisions table
create table prompt_revisions (
  id bigint generated by default as identity primary key,
  prompt_id bigint references prompts(id) on delete cascade not null,
  title text not null,
  content text not null,
  category text not null,
  type text not null,
  tags text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table prompt_revisions enable row level security;

-- Policies
create policy "Enable read access for all users" on prompt_revisions for select using (true);
create policy "Enable insert access for all users" on prompt_revisions for insert with check (true);
create policy "Enable update access for all users" on prompt_revisions for update using (true);
create policy "Enable delete access for all users" on prompt_revisions for delete using (true);
