-- ============================================================
-- BOB Prompt Library — Database Migration
-- Run this in Supabase SQL Editor to apply ALL pending changes
-- WITHOUT dropping existing data.
-- ============================================================

-- 1. Add missing `color` column to taxonomy tables (safe, idempotent)
ALTER TABLE categories  ADD COLUMN IF NOT EXISTS color jsonb;
ALTER TABLE types       ADD COLUMN IF NOT EXISTS color jsonb;
ALTER TABLE prompt_tags ADD COLUMN IF NOT EXISTS color jsonb;

-- 2. Seed default categories (only if table is empty or name doesn't exist)
INSERT INTO categories (name, color) VALUES
  ('Business',     '{"bg":"bg-blue-100","text":"text-blue-700","border":"border-blue-200"}'),
  ('Coding',       '{"bg":"bg-pink-100","text":"text-pink-700","border":"border-pink-200"}'),
  ('Copywriting',  '{"bg":"bg-green-100","text":"text-green-700","border":"border-green-200"}'),
  ('Marketing',    '{"bg":"bg-red-100","text":"text-red-700","border":"border-red-200"}'),
  ('Psicologia',   '{"bg":"bg-purple-100","text":"text-purple-700","border":"border-purple-200"}')
ON CONFLICT (name) DO NOTHING;

-- 3. Seed default types
INSERT INTO types (name, color) VALUES
  ('Esempio one-shot',  '{"bg":"bg-orange-100","text":"text-orange-700","border":"border-orange-200"}'),
  ('Prompt parziale',   '{"bg":"bg-cyan-100","text":"text-cyan-700","border":"border-cyan-200"}'),
  ('Prompt template',   '{"bg":"bg-amber-100","text":"text-amber-700","border":"border-amber-200"}'),
  ('System Prompt',     '{"bg":"bg-indigo-100","text":"text-indigo-700","border":"border-indigo-200"}')
ON CONFLICT (name) DO NOTHING;

-- 4. Seed default tags
INSERT INTO prompt_tags (name) VALUES
  ('contesto'), ('esempio'), ('istruzioni'), ('output'), ('variabili')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- OPTIONAL: Migrate prompts table to sequential BIGINT IDs
-- WARNING: This DELETES all existing data. Export first!
-- Only run if you want numeric sequential IDs starting from 6.
-- ============================================================
/*
DROP TABLE IF EXISTS prompt_revisions CASCADE;
DROP TABLE IF EXISTS prompts CASCADE;

CREATE TABLE prompts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 6) PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL,
  type TEXT NOT NULL,
  is_favorite BOOLEAN DEFAULT FALSE,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE prompt_revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prompt_id BIGINT REFERENCES prompts(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL,
  type TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE prompts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE prompt_revisions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Accesso totale" ON prompts          FOR ALL USING (true);
CREATE POLICY "Accesso totale" ON prompt_revisions FOR ALL USING (true);
*/
